{% set version = "1.3.262" %}

package:
  name: vulkan-tools
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8c77d02694d0516ae2ba3f3718745647e87e788ef93faabb2e3674ff32608010

build:
  # osx requires MotlenVK which we do not package at conda-forge (yet?)
  # it may be that one can patch out the requirements to get the command
  # vulkaninfo to work correctly
  skip: true  # [osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config   # [unix]
    - make         # [unix]
    - ninja        # [win]
    - glslang
  host:
    - libvulkan-headers  {{ version }}
    - libvulkan-loader   {{ version }}
    - wayland              # [linux]
    - wayland-protocols    # [linux]
    - xorg-libx11          # [linux]
    - xorg-libxrandr       # [linux]
    - libxcb               # [linux]
  run:
    - libvulkan-loader   {{ version }}

test:
  commands:
    - which vulkaninfo   # [unix]
    - where vulkaninfo   # [win]

about:
  home: https://github.com/KhronosGroup/Vulkan-Tools/
  summary: Vulkan tools and utilities that can assist development
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hmaarrfk
