{% set version = "1.4.304" %}

package:
  name: vulkan-tools
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fa17870f531affec06dfd5cab8121cb6e54777f779dab59fccafeb136fe43e19
  patches: cube-CMakeLists.txt.patch

build:
  # osx requires MotlenVK which we do not package at conda-forge (yet?)
  # it may be that one can patch out the requirements to get the command
  # vulkaninfo to work correctly
  skip: true  # [osx]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config   # [unix]
    - make         # [unix]
    - ninja        # [win]
    - glslang
  host:
    - libvulkan-headers  {{ version }}
    - libvulkan-loader   {{ version }}
    - vulkan-volk
    - wayland              # [linux]
    - wayland-protocols    # [linux]
    - xorg-libx11          # [linux]
    - xorg-libxrandr       # [linux]
    - xorg-xorgproto       # [linux]
    - libxcb               # [linux]
  run:
    - libvulkan-loader   {{ version }}

test:
  commands:
    - which vulkaninfo   # [unix]
    - where vulkaninfo   # [win]

about:
  home: https://github.com/KhronosGroup/Vulkan-Tools/
  summary: Vulkan tools and utilities that can assist development
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - JarrettSJohnson
    - hmaarrfk
    # eunos-1128 is interested in aarch64 and ppc64le
    - eunos-1128
