# For this repo, v**** tags exists, but apparently the stable tags (the one corresponding to versions
# that are available for download at https://vulkan.lunarg.com/sdk/home) are the vulkan-sdk-*** ones
# See https://github.com/KhronosGroup/Vulkan-Headers#version-tagging-scheme
{% set version = "1.4.328.1" %}

package:
  name: vulkan-tools
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/vulkan-sdk-{{ version }}.tar.gz
  sha256: 617e91b396ac771869d62cd131f05dcc0b82d038744dab7f575bcf213852f8bf

build:
  # osx requires MotlenVK which we do not package at conda-forge (yet?)
  # it may be that one can patch out the requirements to get the command
  # vulkaninfo to work correctly
  skip: true  # [osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config   # [unix]
    - make         # [unix]
    - ninja        # [win]
    - glslang
  host:
    - libvulkan-headers  {{ version }}
    - libvulkan-loader   {{ version }}
    - vulkan-volk
    - wayland              # [linux]
    - wayland-protocols    # [linux]
    - xorg-libx11          # [linux]
    - xorg-libxrandr       # [linux]
    - xorg-xorgproto       # [linux]
    - libxcb               # [linux]
  run:
    - libvulkan-loader   {{ version }}

test:
  commands:
    - which vulkaninfo   # [unix]
    - where vulkaninfo   # [win]

about:
  home: https://github.com/KhronosGroup/Vulkan-Tools/
  summary: Vulkan tools and utilities that can assist development
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - traversaro
    - JarrettSJohnson
    - hmaarrfk
