# For this repo, v**** tags exists, but apparently the stable tags (the one corresponding to versions
# that are available for download at https://vulkan.lunarg.com/sdk/home) are the vulkan-sdk-*** ones
# See https://github.com/KhronosGroup/Vulkan-Headers#version-tagging-scheme
{% set version = "1.4.341.0" %}

package:
  name: vulkan-tools
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/vulkan-sdk-{{ version }}.tar.gz
  sha256: dc65f1ea97dd0b2155c2281a79e87d27183c0737fb96377744091a3c8460ae1e
  patches:
    - use-system-icd.patch  # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - glslang
    - make         # [unix]
    - ninja        # [win]
    - pkg-config   # [unix]
  host:
    - libvulkan-headers  {{ version }}
    - libvulkan-loader   {{ version }}
    - wayland              # [linux]
    - wayland-protocols    # [linux]
    - xorg-libx11          # [linux]
    - xorg-libxrandr       # [linux]
    - xorg-xorgproto       # [linux]
    - libxcb               # [linux]
  run:
    - libvulkan-loader   {{ version }}

test:
  commands:
    - which vulkaninfo   # [unix]
    - where vulkaninfo   # [win]

about:
  home: https://github.com/KhronosGroup/Vulkan-Tools/
  summary: Vulkan tools and utilities that can assist development
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - traversaro
    - JarrettSJohnson
    - hmaarrfk
    # eunos-1128 is interested in aarch64 and ppc64le
    - eunos-1128
